FROM nginx:latest

# Copy the Nginx configuration file
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Create directories for static and media files
RUN mkdir -p /app/static /app/media

# Expose port 80
EXPOSE 80
