# Rasmiy NGINX tasvirini ishlatish
FROM nginx:latest

# O'zgarilgan NGINX konfiguratsiya faylini konteynerga nusxalash
# Odatda webbot.conf fayli /etc/nginx/ papkaga joylashtiriladi
COPY nginx.conf /etc/nginx/nginx.conf
COPY default.conf /etc/nginx/conf.d/default.conf

# Statik va media fayllar uchun papkalarni yaratish
RUN mkdir -p /app/static /app/media

# Port 80 ni ochish
EXPOSE 80

