events {
    worker_connections 1024;
}

http {
    server {
        listen 80;
        server_name localhost;  # yoki 127.0.0.1

        # Asosiy web ilovaga proxy qilish
        location / {
            proxy_pass http://127.0.0.1:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_read_timeout 120s;
            proxy_connect_timeout 120s;
            proxy_http_version 1.1;
        }

        # Statik fayllarni to'g'ri xizmat qilish (Linux tizimida)
        location /static/ {
            alias /app/static/;  # Linux tizimi uchun mos yo'l
        }

        # Media fayllarni to'g'ri xizmat qilish (Linux tizimida)
        location /media/ {
            alias /app/media/;  # Linux tizimi uchun mos yo'l
        }

        # Xato sahifalar
        error_page 404 /404.html;
        location = /404.html {
            root /usr/share/nginx/html;  # Xato sahifalar uchun yo'l
            internal;
        }
    }
}
